//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaExtractor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaExtractor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutCloseButton {
            get {
                return ResourceManager.GetString("AboutCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AboutDate {
            get {
                return ResourceManager.GetString("AboutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Extractor is an application to preview and extract packed media in Microsoft Office files (e.g. Word, PowerPoint or Excel documents) or common archives (e.g. zip, 7z or tar).
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Media-Extractor.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string AboutWebsite {
            get {
                return ResourceManager.GetString("AboutWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File(s).
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all Files.
        /// </summary>
        public static string ButtonSaveAll {
            get {
                return ResourceManager.GetString("ButtonSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save selected File(s).
        /// </summary>
        public static string ButtonSaveSelected {
            get {
                return ResourceManager.GetString("ButtonSaveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC32 (cyclic redundancy check) is a simple hashing method to compare whether data or files are identical. However, CRC does not provide a 100% guarantee that two files are identical. But it is a strong evidence if the size of both files are identical and no malicious tampering is to be expected..
        /// </summary>
        public static string CrcDescription {
            get {
                return ResourceManager.GetString("CrcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Extraction.
        /// </summary>
        public static string DialogButtonCancel {
            get {
                return ResourceManager.GetString("DialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the extraction.
        /// </summary>
        public static string DialogButtonCancelTooltip {
            get {
                return ResourceManager.GetString("DialogButtonCancelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string DialogButtonOverwrite {
            get {
                return ResourceManager.GetString("DialogButtonOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the existing file.
        /// </summary>
        public static string DialogButtonOverwriteTooltip {
            get {
                return ResourceManager.GetString("DialogButtonOverwriteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string DialogButtonRename {
            get {
                return ResourceManager.GetString("DialogButtonRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename the new file.
        /// </summary>
        public static string DialogButtonRenameTooltip {
            get {
                return ResourceManager.GetString("DialogButtonRenameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string DialogButtonSkip {
            get {
                return ResourceManager.GetString("DialogButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip the extraction of the file.
        /// </summary>
        public static string DialogButtonSkipTooltip {
            get {
                return ResourceManager.GetString("DialogButtonSkipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string DialogCancelTitle {
            get {
                return ResourceManager.GetString("DialogCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogErrorTitle {
            get {
                return ResourceManager.GetString("DialogErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; could not be opened.
        /// </summary>
        public static string DialogExplorerError {
            get {
                return ResourceManager.GetString("DialogExplorerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists....
        /// </summary>
        public static string DialogHeader {
            get {
                return ResourceManager.GetString("DialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the retrieval of the file extensions for the previews. The default values are restored.
        /// </summary>
        public static string DialogInvalidExtensions {
            get {
                return ResourceManager.GetString("DialogInvalidExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC32:.
        /// </summary>
        public static string DialogLabelCrc {
            get {
                return ResourceManager.GetString("DialogLabelCrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string DialogLabelDate {
            get {
                return ResourceManager.GetString("DialogLabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing File.
        /// </summary>
        public static string DialogLabelExisting {
            get {
                return ResourceManager.GetString("DialogLabelExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string DialogLabelName {
            get {
                return ResourceManager.GetString("DialogLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File to Extract.
        /// </summary>
        public static string DialogLabelNew {
            get {
                return ResourceManager.GetString("DialogLabelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string DialogLabelSize {
            get {
                return ResourceManager.GetString("DialogLabelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be loaded.\n{0}\nError Message: {1}.
        /// </summary>
        public static string DialogLoadFailure {
            get {
                return ResourceManager.GetString("DialogLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Office Formats|*.docx;*.dotx;*.docm;*.dotm;*.xlsx;*.xlsm;*.xlsb;*.xltx;*.xltm;*.pptx;*.pptm;*.potx;*.potm;*.ppsx;*.ppsm|Word documents|*.docx;*.dotx;*.docm;*.dotm|Excel documents|*.xlsx;*.xlsm;*.xlsb;*.xltx;*.xltm|PowerPoint documents|*.pptx;*.pptm;*.potx;*.potm;*.ppsx;*.ppsm|Common Archive Formats|*.zip;*.7z;*.rar;*.bzip2,*.gz;*.tar;*.cab;*.chm;*.lzh;*.iso|All files|*.*.
        /// </summary>
        public static string DialogLoadFilter {
            get {
                return ResourceManager.GetString("DialogLoadFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Office Document....
        /// </summary>
        public static string DialogLoadTitle {
            get {
                return ResourceManager.GetString("DialogLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change log &apos;{0}&apos; was not found..
        /// </summary>
        public static string DialogMissingChangelog {
            get {
                return ResourceManager.GetString("DialogMissingChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog not found.
        /// </summary>
        public static string DialogMissingChangelogTitle {
            get {
                return ResourceManager.GetString("DialogMissingChangelogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license file &apos;{0}&apos; was not found..
        /// </summary>
        public static string DialogMissingLicense {
            get {
                return ResourceManager.GetString("DialogMissingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License could not be found.
        /// </summary>
        public static string DialogMissingLicenseTitle {
            get {
                return ResourceManager.GetString("DialogMissingLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not found:\n{0}\nShould the entry be removed from the recent file list?.
        /// </summary>
        public static string DialogMissingRecentFile {
            get {
                return ResourceManager.GetString("DialogMissingRecentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project website could not be loaded.
        /// </summary>
        public static string DialogMissingWebsite {
            get {
                return ResourceManager.GetString("DialogMissingWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project website not loaded.
        /// </summary>
        public static string DialogMissingWebsiteTitle {
            get {
                return ResourceManager.GetString("DialogMissingWebsiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Decision.
        /// </summary>
        public static string DialogRememberCheckbox {
            get {
                return ResourceManager.GetString("DialogRememberCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Folder to save all Files....
        /// </summary>
        public static string DialogSaveAllTitle {
            get {
                return ResourceManager.GetString("DialogSaveAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current File as....
        /// </summary>
        public static string DialogSaveCurrentTitle {
            get {
                return ResourceManager.GetString("DialogSaveCurrentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all files were extracted.
        /// </summary>
        public static string DialogSaveErrors {
            get {
                return ResourceManager.GetString("DialogSaveErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be saved.
        /// </summary>
        public static string DialogSaveFailure {
            get {
                return ResourceManager.GetString("DialogSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files|*.*.
        /// </summary>
        public static string DialogSaveFilter {
            get {
                return ResourceManager.GetString("DialogSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Folder to save the selected Files....
        /// </summary>
        public static string DialogSaveSelectedTitle {
            get {
                return ResourceManager.GetString("DialogSaveSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preview of a large file (&gt; {0}) is attempted.\nThis process may take a long time.\nShall the preview be created?.
        /// </summary>
        public static string DialogSizeWarning {
            get {
                return ResourceManager.GetString("DialogSizeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to preview a large File....
        /// </summary>
        public static string DialogSizeWarningTitle {
            get {
                return ResourceManager.GetString("DialogSizeWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error during the extraction:.
        /// </summary>
        public static string DialogUnexpectedError {
            get {
                return ResourceManager.GetString("DialogUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Document here.
        /// </summary>
        public static string DropAreaWatermark {
            get {
                return ResourceManager.GetString("DropAreaWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded Files.
        /// </summary>
        public static string LabelListview {
            get {
                return ResourceManager.GetString("LabelListview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string LabelPreview {
            get {
                return ResourceManager.GetString("LabelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext..
        /// </summary>
        public static string ListViewColumnExtension {
            get {
                return ResourceManager.GetString("ListViewColumnExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename (Embedded).
        /// </summary>
        public static string ListViewColumnName {
            get {
                return ResourceManager.GetString("ListViewColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Path.
        /// </summary>
        public static string ListViewColumnPath {
            get {
                return ResourceManager.GetString("ListViewColumnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ListViewColumnSize {
            get {
                return ResourceManager.GetString("ListViewColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string MenuAppearance {
            get {
                return ResourceManager.GetString("MenuAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string MenuAppearanceDarkmode {
            get {
                return ResourceManager.GetString("MenuAppearanceDarkmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuAppearanceLanguage {
            get {
                return ResourceManager.GetString("MenuAppearanceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Language (Default).
        /// </summary>
        public static string MenuAppearanceLanguageDefault {
            get {
                return ResourceManager.GetString("MenuAppearanceLanguageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MenuAppearanceLanguageEnglish {
            get {
                return ResourceManager.GetString("MenuAppearanceLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français (French).
        /// </summary>
        public static string MenuAppearanceLanguageFrench {
            get {
                return ResourceManager.GetString("MenuAppearanceLanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch (German).
        /// </summary>
        public static string MenuAppearanceLanguageGerman {
            get {
                return ResourceManager.GetString("MenuAppearanceLanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (日本語).
        /// </summary>
        public static string MenuAppearanceLanguageJapanese {
            get {
                return ResourceManager.GetString("MenuAppearanceLanguageJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español (Spanish).
        /// </summary>
        public static string MenuAppearanceLanguageSpanish {
            get {
                return ResourceManager.GetString("MenuAppearanceLanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string MenuDocument {
            get {
                return ResourceManager.GetString("MenuDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Preview on unknown File Formats.
        /// </summary>
        public static string MenuDocumentGenerictextPreview {
            get {
                return ResourceManager.GetString("MenuDocumentGenerictextPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Folder Structure when Extracting.
        /// </summary>
        public static string MenuDocumentKeepStructure {
            get {
                return ResourceManager.GetString("MenuDocumentKeepStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Explorer after Extracting.
        /// </summary>
        public static string MenuDocumentOpenExplorer {
            get {
                return ResourceManager.GetString("MenuDocumentOpenExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show embedded Image Files.
        /// </summary>
        public static string MenuDocumentShowImages {
            get {
                return ResourceManager.GetString("MenuDocumentShowImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show other embedded Files.
        /// </summary>
        public static string MenuDocumentShowOther {
            get {
                return ResourceManager.GetString("MenuDocumentShowOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Warning for Preview of large Files.
        /// </summary>
        public static string MenuDocumentSizeWarning {
            get {
                return ResourceManager.GetString("MenuDocumentSizeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        public static string MenuFileClearRecent {
            get {
                return ResourceManager.GetString("MenuFileClearRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document.
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MenuFileQuit {
            get {
                return ResourceManager.GetString("MenuFileQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string MenuFileRecent {
            get {
                return ResourceManager.GetString("MenuFileRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all Files.
        /// </summary>
        public static string MenuFileSaveAll {
            get {
                return ResourceManager.GetString("MenuFileSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save selected File(s).
        /// </summary>
        public static string MenuFileSaveSelected {
            get {
                return ResourceManager.GetString("MenuFileSaveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log.
        /// </summary>
        public static string MenuHelpChangeLog {
            get {
                return ResourceManager.GetString("MenuHelpChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string MenuHelpLicense {
            get {
                return ResourceManager.GetString("MenuHelpLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Website.
        /// </summary>
        public static string MenuHelpWebsite {
            get {
                return ResourceManager.GetString("MenuHelpWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} loaded.
        /// </summary>
        public static string StatusEmbeddedLoaded {
            get {
                return ResourceManager.GetString("StatusEmbeddedLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loaded: {0}.
        /// </summary>
        public static string StatusLoaded {
            get {
                return ResourceManager.GetString("StatusLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded file could not be loaded: {0}.
        /// </summary>
        public static string StatusLoadEmbeddedImageFailure {
            get {
                return ResourceManager.GetString("StatusLoadEmbeddedImageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preview image for &apos;{0}&apos; could not be loaded. Displaying as text.
        /// </summary>
        public static string StatusLoadEmbeddedImageFallback {
            get {
                return ResourceManager.GetString("StatusLoadEmbeddedImageFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview not possible for {0}.
        /// </summary>
        public static string StatusLoadEmbeddedOtherFailure {
            get {
                return ResourceManager.GetString("StatusLoadEmbeddedOtherFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preview for &apos;{0}&apos; could not be loaded. Displaying as text.
        /// </summary>
        public static string StatusLoadEmbeddedOtherFallback {
            get {
                return ResourceManager.GetString("StatusLoadEmbeddedOtherFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text / XML file could not be loaded: {0}.
        /// </summary>
        public static string StatusLoadEmbeddedTextFailure {
            get {
                return ResourceManager.GetString("StatusLoadEmbeddedTextFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be loaded.
        /// </summary>
        public static string StatusLoadFailure {
            get {
                return ResourceManager.GetString("StatusLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file... Please wait.
        /// </summary>
        public static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading embedded file... Please wait.
        /// </summary>
        public static string StatusLoadingEmbedded {
            get {
                return ResourceManager.GetString("StatusLoadingEmbedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preview of &apos;{0}&apos; was skipped (file too large).
        /// </summary>
        public static string StatusPreviewSkipped {
            get {
                return ResourceManager.GetString("StatusPreviewSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save process was canceled.
        /// </summary>
        public static string StatusSaveCanceled {
            get {
                return ResourceManager.GetString("StatusSaveCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files extracted ({1} overwritten, {2} renamed), {3} skipped, {4} not extracted (errors).
        /// </summary>
        public static string StatusSaveErrorSummary {
            get {
                return ResourceManager.GetString("StatusSaveErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the file: {0}.
        /// </summary>
        public static string StatusSaveFailure {
            get {
                return ResourceManager.GetString("StatusSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was saved as: {0}.
        /// </summary>
        public static string StatusSaveSuccess {
            get {
                return ResourceManager.GetString("StatusSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files extracted ({1} overwritten, {2} renamed), {3} skipped.
        /// </summary>
        public static string StatusSaveSummary {
            get {
                return ResourceManager.GetString("StatusSaveSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image preview could not be created.
        /// </summary>
        public static string TextErrorInvalidImage {
            get {
                return ResourceManager.GetString("TextErrorInvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text preview could not be created.
        /// </summary>
        public static string TextErrorInvalidText {
            get {
                return ResourceManager.GetString("TextErrorInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files could not be extracted..
        /// </summary>
        public static string TextErrorMultipleFiles {
            get {
                return ResourceManager.GetString("TextErrorMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One file could not be extracted..
        /// </summary>
        public static string TextErrorOneFile {
            get {
                return ResourceManager.GetString("TextErrorOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file may be not a valid Office file or archive..
        /// </summary>
        public static string TextInvalidFormat {
            get {
                return ResourceManager.GetString("TextInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like the filename is not valid. Please check the file name and path..
        /// </summary>
        public static string TextInvalidPath {
            get {
                return ResourceManager.GetString("TextInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that the file is not open in another application..
        /// </summary>
        public static string TextLockedFile {
            get {
                return ResourceManager.GetString("TextLockedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Preview.
        /// </summary>
        public static string TextNoPreview {
            get {
                return ResourceManager.GetString("TextNoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; could not be opened.
        /// </summary>
        public static string TextSaveError {
            get {
                return ResourceManager.GetString("TextSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were skipped..
        /// </summary>
        public static string TextSkippedMultipleFiles {
            get {
                return ResourceManager.GetString("TextSkippedMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One file was skipped..
        /// </summary>
        public static string TextSkippedOneFile {
            get {
                return ResourceManager.GetString("TextSkippedOneFile", resourceCulture);
            }
        }
    }
}
